<a href="https://colab.research.google.com/github/catssci/TIL/blob/main/Python/numpy/augmentation_(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
array = np.arange(30)
array = array.reshape(5, -1)

In [12]:
print("------ 원본 data -----")
print(array)

------ 원본 data -----
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


## 01. numpy.rot90

In [15]:
array90 = np.rot90(array, 1)
array180 = np.rot90(array, 2)
array270 = np.rot90(array, 3)

In [14]:
print("왼쪽으로 90도 회전")
print(array90)

[[ 5 11 17 23 29]
 [ 4 10 16 22 28]
 [ 3  9 15 21 27]
 [ 2  8 14 20 26]
 [ 1  7 13 19 25]
 [ 0  6 12 18 24]]


In [16]:
print("왼쪽으로 180도 회전")
print(array180)

왼쪽으로 180도 회전
[[29 28 27 26 25 24]
 [23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


In [18]:
print("왼쪽으로 270도 회전")
print(array270)

왼쪽으로 270도 회전
[[24 18 12  6  0]
 [25 19 13  7  1]
 [26 20 14  8  2]
 [27 21 15  9  3]
 [28 22 16 10  4]
 [29 23 17 11  5]]


## 02. numpy.roll

In [39]:
array_shift_right = np.roll(array, 1, axis=1)
array_shift_left = np.roll(array, -1, axis=1)

array_shift_up = np.roll(array, -1, axis=0)
array_shift_down = np.roll(array, 1, axis=0)

array_shift = np.roll(array, 1)

array_shift_right_and_down = np.roll(array, (2, 1), axis=(1, 0))

In [29]:
print("우측으로 1 만큼 shift")
print(array_shift_right)

우측으로 1 만큼 shift
[[ 5  0  1  2  3  4]
 [11  6  7  8  9 10]
 [17 12 13 14 15 16]
 [23 18 19 20 21 22]
 [29 24 25 26 27 28]]


In [30]:
print("좌측으로 1 만큼 shift")
print(array_shift_left)

좌측으로 1 만큼 shift
[[ 1  2  3  4  5  0]
 [ 7  8  9 10 11  6]
 [13 14 15 16 17 12]
 [19 20 21 22 23 18]
 [25 26 27 28 29 24]]


In [31]:
print("위로 1 만큼 shift")
print(array_shift_up)

위로 1 만큼 shift
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [ 0  1  2  3  4  5]]


In [32]:
print("아래로 1 만큼 shift")
print(array_shift_down)

아래로 1 만큼 shift
[[24 25 26 27 28 29]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [37]:
print("원소 단위로 shift")
print(array_shift)

원소 단위로 shift
[[29  0  1  2  3  4]
 [ 5  6  7  8  9 10]
 [11 12 13 14 15 16]
 [17 18 19 20 21 22]
 [23 24 25 26 27 28]]


In [40]:
print("우측으로 2 shift, 아래로 1 shift")
print(array_shift_right_and_down)

우측으로 2 shift, 아래로 1 shift
[[28 29 24 25 26 27]
 [ 4  5  0  1  2  3]
 [10 11  6  7  8  9]
 [16 17 12 13 14 15]
 [22 23 18 19 20 21]]


## 03. numpy.flip

In [56]:
array_vertically = np.flip(array, 0)
array_horizontally = np.flip(array, 1)

array_vertic_horizon = np.flip(array, (0, 1))

In [50]:
print("vertical flip")
print(array_vertically)
print("\n\n = numpy.flipud")
print(np.flipud(array))

vertical flip
[[24 25 26 27 28 29]
 [18 19 20 21 22 23]
 [12 13 14 15 16 17]
 [ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]


 = numpy.flipud
[[24 25 26 27 28 29]
 [18 19 20 21 22 23]
 [12 13 14 15 16 17]
 [ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]


In [51]:
print("horizontally flip")
print(array_horizontally)
print("\n\n = numpy.fliplr")
print(np.fliplr(array))

horizontally flip
[[ 5  4  3  2  1  0]
 [11 10  9  8  7  6]
 [17 16 15 14 13 12]
 [23 22 21 20 19 18]
 [29 28 27 26 25 24]]


 = numpy.fliplr
[[ 5  4  3  2  1  0]
 [11 10  9  8  7  6]
 [17 16 15 14 13 12]
 [23 22 21 20 19 18]
 [29 28 27 26 25 24]]


In [57]:
print("vertically and horizontally flip")
print(array_vertic_horizon)

vertically and horizontally flip
[[29 28 27 26 25 24]
 [23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


## Summay

- roll, flip은 numpy array의 shape를 변화하지 않는다.
- rot90은 numpy array의 shape를 변화 가능

In [59]:
array.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [60]:
print(array.shape)
print(array.T.shape)

(5, 6)
(6, 5)
